# Generated by Django 3.2.7 on 2021-10-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraCompraModel',
            fields=[
                ('cabeceraId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('cabeceraFecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'db_table': 'cabecera_compra',
            },
        ),
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('categoriaId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('categoriaNombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('clienteId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('clienteNombre', models.CharField(db_column='nombre', max_length=50)),
                ('clienteTipoDoc', models.TextField(choices=[(1, 'DNI'), (2, 'PASAPORTE')], db_column='tipo_doc')),
                ('clienteNroDoc', models.IntegerField(db_column='nro_doc', unique=True)),
                ('clienteDireccion', models.CharField(db_column='direccion', max_length=100)),
                ('clienteTipo', models.TextField(choices=[(1, 'ADMINISTRADOR'), (2, 'CLIENTE')], db_column='tipo')),
                ('clienteCorreo', models.EmailField(db_column='correo', max_length=50, unique=True)),
                ('clientePassword', models.TextField()),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoModel',
            fields=[
                ('metodoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('metodoTipo', models.TextField(choices=[(1, 'EFECTIVO'), (2, 'TARJETA')], db_column='tipoDoc')),
                ('metodoNro', models.IntegerField(db_column='nro')),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('productoNombre', models.CharField(db_column='nombre', max_length=50)),
                ('productoDescripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('productoCantidad', models.IntegerField(db_column='cantidad', default=0)),
                ('productoEstado', models.BooleanField(db_column='estado', default=True)),
                ('productoImagen', models.ImageField(db_column='foto', upload_to='productos/')),
                ('productoPrecio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=5)),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_At', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='categoriaProducto', to='handmade.categoriamodel')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('pedidoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pedidoFecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('pedidoTotal', models.DecimalField(db_column='total', decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidoCliente', to='handmade.clientemodel')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalleModel',
            fields=[
                ('detalleId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('detalleCantidad', models.IntegerField(db_column='cantidad', default=0)),
                ('detallePrecioUnitario', models.DecimalField(db_column='precioUnitario', decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='detallePedido', to='handmade.pedidomodel')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalleProducto', to='handmade.productomodel')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraModel',
            fields=[
                ('detalleCompraId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('detalleCompraCantidad', models.IntegerField(db_column='cantidad', default=0)),
                ('detalleCompraPrecioTotal', models.DecimalField(db_column='precioTotal', decimal_places=2, max_digits=5)),
                ('cabecera', models.ForeignKey(db_column='cabecera_id', on_delete=django.db.models.deletion.PROTECT, related_name='cabeceraDetalle', to='handmade.cabeceracompramodel')),
                ('metodo', models.ForeignKey(db_column='metodo_id', on_delete=django.db.models.deletion.PROTECT, related_name='metodoCompra', to='handmade.metodopagomodel')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalleProductoCompra', to='handmade.productomodel')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='CarritoModel',
            fields=[
                ('carritoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('carritoFechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='carritoCliente', to='handmade.clientemodel')),
                ('productos', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='carritoProductos', to='handmade.productomodel')),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.AddField(
            model_name='cabeceracompramodel',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='cabeceraCliente', to='handmade.clientemodel'),
        ),
    ]
