# Generated by Django 3.2.7 on 2021-10-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0001_creacion_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='categoriaNombre',
            field=models.CharField(db_column='nombre', max_length=50, unique=True),
        ),
    ]
