# Generated by Django 3.2.7 on 2021-10-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemodel',
            name='clientePassword',
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='password',
            field=models.TextField(),
        ),
    ]
